version: '3.8'
services:
  backend:
    build: ./backend-server
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - mongodb+srv://cornelkoschat:Passwort@abschlussprojekt2024.izzkh.mongodb.net/?retryWrites=true&w=majority&appName=Abschlussprojekt2024

  frontend:
    build: ./website
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
